### PR TITLE
Avoid reporting "Executing command" as an unknown build error

### LINKED ISSUE #200: Diagnostics message is always printed to MSBuild log as an "Unknown build error"
The message 
> Unknown build error: Executing command

 is always written as a "normal" severity message
It's generated here: https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTaskInternal.cs#L317
It has no error code, so it's get assigned an AC1000 code and the error prefix here: https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTask.cs#L207-L212
And then printed to the build output here: https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTask.cs#L226

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #200

### CODE REVIEW

File: runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTask.cs [hunk 1]
```diff
@@ -207,8 +207,16 @@ private void ProcessBuildMessage(BuildMessage message)
             errorCode = Log.ExtractMessageCode(message.Message, out logMessage);
             if (string.IsNullOrEmpty(errorCode))
             {
-                errorCode = "AC1000";
-                logMessage = "Unknown build error: " + message.Message;
+                if (message.Message.StartsWith("Executing command:") && message.Severity == TraceLevel.Info)
```
Comment (dosvidos) [inline runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTask.cs]: I suggest to use StringComparison.Ordinal for performance reasons. You don't really want to do locale-aware string comparsions in such code.
